name: Auto Deploy to Render

on:
  push:
    branches: [ main ]   # change this if your deploy branch is not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        env:
          HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploying to Render..."
          curl -X POST -sS "$HOOK"
